// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    copy: typeof import('./src/components/SheetImport copy.vue')['default']
    CopyableText: typeof import('./src/components/CopyableText.vue')['default']
    ElectronVersions: typeof import('./src/components/ElectronVersions.vue')['default']
    Import: typeof import('./src/components/Import.vue')['default']
    ReactiveCounter: typeof import('./src/components/ReactiveCounter.vue')['default']
    ReactiveHash: typeof import('./src/components/ReactiveHash.vue')['default']
    SheetImport: typeof import('./src/components/SheetImport.vue')['default']
    SheetLikes: typeof import('./src/components/SheetLikes.vue')['default']
    SheetSearch: typeof import('./src/components/SheetSearch.vue')['default']
  }
}
